# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
